site_name: OTSO Documentation

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: list
            show_source: false
            show_signature_annotations: true
            separate_signature: true
            show_root_heading: true
            show_root_toc_entry: false

markdown_extensions:
  - md_in_html

nav:
  - Home: index.md
  - Cutoff: Cutoff.md
  - Cone: Cone.md
  - Trajectory: Trajectory.md
  - Planet: Planet.md
  - Flight: Flight.md
  - Magfield: Magfield.md
  - Trace: Trace.md
  - Coordtrans: Coordtrans.md
  - CLI: CLI.md
  - Publications: Publications.md
  